In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.19.0


In [2]:
# 데이터 셋 로드
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
# 모델 빌드
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10, activation="softmax"),
    ]
)

# 문자열 이름을 사용하는 방식
# loss = tf.keras.losses.get("sparse_categorical_crossentropy"): 내부 동작
model.compile(
    optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]
)

/home/chan/code/vscode/tensor-cpp/.venv/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.07885352, 0.09548049, 0.12824948, 0.15525179, 0.11135183,
        0.09010567, 0.11519159, 0.04954241, 0.07259332, 0.10337997]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.09786793, 0.09950878, 0.10282359, 0.10563789, 0.10110072,
        0.09897538, 0.10148966, 0.09504095, 0.09725717, 0.10029796]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.3128843)

In [8]:
model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/home/chan/code/vscode/tensor-cpp/.venv/lib/python3.12/site-packages/keras/src/backend/tensorflow/nn.py:708: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8580 - loss: 0.4896
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9535 - loss: 0.1549
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9660 - loss: 0.1126
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9721 - loss: 0.0907
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9761 - loss: 0.0760


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 975us/step - accuracy: 0.9776 - loss: 0.0767


[0.0767049491405487, 0.9775999784469604]

In [11]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0853374 , 0.08533739, 0.08533741, 0.08534057, 0.08533739,
        0.08533739, 0.08533739, 0.23195907, 0.08533742, 0.08533855],
       [0.08533824, 0.08534709, 0.23194568, 0.08533937, 0.08533823,
        0.08533823, 0.08533823, 0.08533823, 0.08533844, 0.08533823],
       [0.0853607 , 0.2315911 , 0.0853777 , 0.08537008, 0.08536424,
        0.08536069, 0.08536077, 0.08547743, 0.08537596, 0.08536132],
       [0.23195602, 0.08533759, 0.08533826, 0.08533759, 0.08533759,
        0.08533763, 0.08534165, 0.08533762, 0.08533759, 0.08533842],
       [0.08535327, 0.08535162, 0.08535276, 0.08535165, 0.23173389,
        0.08535165, 0.08535182, 0.08535965, 0.08535164, 0.08544209]],
      dtype=float32)>